## **Assignment - Week 3**

**Instructions:** 
- Answer each question on a separate cell, either in a markdown or code cell depending on the question.
- Use comments in your code

In [2]:
import numpy as np #importing the module to perform scientific computation

### **Question 1**

 Demonstrate how to create a 1-dimensional, 2-dimensional, and 3-dimensional numpy arrays using `np.array`. Use any suitable data for the arrays and display each. The 1 dimensional, 2 dimensional and 3 dimensional arrays you created should have shapes of ```(7,), (4, 4), and (3, 2, 3)``` respectively. Print out the shapes of each array after you have created them.

In [4]:

array_1d = np.array([3, 2, 5, 8, 2, 1, 5]) #creating one dimensional array
array_2d = np.array([[1,6,8,3],
                    [3, 5, 6, 2],
                     [4, 5, 2, 9],
                     [3, 8, 9, 0]
                    ]) # creating two dimensional array

array_3d = np.array(
    [[[3, 3, 6],
     [3, 5, 8]], # first block of the 3 dimensional array
      
      
        
        [[4, 6, 5],
        [3, 8, 2]], # second block of the 3 dimensional array
         
        [[3, 6, 8],
         [4, 3, 2] # third block of the 3 dimensional array 
        ]]
)

print(array_1d.shape) # printing the 1 dimensional array
print(array_2d.shape) # printing the 2 dimensional array 
print(array_3d.shape) # printing the 3 dimensional array

(7,)
(4, 4)
(3, 2, 3)


### **Question 2**

**2a.** Write a Python code to create two arrays using `np.zeros` and `np.ones` with a shape of (4, 5). Print both arrays.\
**2b.** Using the `np.arange` function, create an array from `10 - 36` \
**2c.** Generate a numpy array with `25` linearly spaced values ranging from `20 to 50` using `np.linspace`. Print the array.

In [6]:
# Question 2a
array_zeros = np.zeros((4, 5)) # creating arrays with shape 4 x 5 of zeros
array_ones = np.ones((4, 5))  # creating arrays with shape 4 x 5 of ones
print('Arrays of zeros')
print(array_zeros) # printing the array of zeros
print('Arrays of ones')
print(array_ones) # printing the arrays of ones

Arrays of zeros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Arrays of ones
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# Questiond 2b
print("Arrays of numbers from 10 - 37")
array_arrange = np.arange(10, 37) # creation of arrays between 10 to 36 using the arrange numpy function
print(array_arrange) # printing the array on the terminal 

Arrays of numbers from 10 - 37
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36]


In [8]:
linear_array = np.linspace(20, 50, 25) # creating linearly spaced array

print(linear_array) # Print the array


[20.   21.25 22.5  23.75 25.   26.25 27.5  28.75 30.   31.25 32.5  33.75
 35.   36.25 37.5  38.75 40.   41.25 42.5  43.75 45.   46.25 47.5  48.75
 50.  ]


### **Question 3**

Consider the numpy array below. Write a Python code to extract the sub-array containing the third to fifth elements.
```python
arr = np.array([23, 54, 32, 33, 56, 78, 77, 45, 33])
```

In [10]:
arr = np.array([23, 54, 32, 33, 56, 78, 77, 45, 33])
sub_arr = arr[2: 5] # slicing the array
print(f'This is the sub array: {sub_arr}') # printing the sliced array

This is the sub array: [32 33 56]


### **Question 4**

Given the 2-dimensional numpy array below, demonstrate how to slice and obtain the third row and first and second column.

```python
arr_2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9],
                  [4, 5, 3]])
```

In [12]:
arr_2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9],
                  [4, 5, 3]])

slice_arr = arr_2d[2:-1, 0:2] #  slice and obtain the third row and first and second column.
print(slice_arr) #printing the sliced array

[[7 8]]


### **Question 5**

Given the 3d array below, answer the following questions:\
**5a.** What is the shape of the array and how many layers or blocks does the array have?\
**5b.** Slice out the second and last rows from the third block using array slicing.
```python
array_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9], 
     [2, 3, 3]],
    
    [[13, 14, 15], 
     [16, 17, 18], 
     [19, 20, 21], 
     [22, 23, 24]],
    
    [[25, 26, 27], 
     [28, 29, 30], 
     [31, 32, 33], 
     [34, 35, 36]]])
```

### The shape of the array and the numbers of the blocks layer in the array

- The shape of the array is (3, 4, 3)
- The blocks in the array is 3 blocks

In [15]:
# question 5b
array_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9], 
     [2, 3, 3]],
    
    [[13, 14, 15], 
     [16, 17, 18], 
     [19, 20, 21], 
     [22, 23, 24]],
    
    [[25, 26, 27], 
     [28, 29, 30], 
     [31, 32, 33], 
     [34, 35, 36]]])


block_slice = array_3d[[2], [1,-1]] # Slicing out the second and last rows from the third block using array slicing.
print(block_slice) # printing the sliced block 

[[28 29 30]
 [34 35 36]]
